version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: expense_management_application_local
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
    volumes:
      - ./mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: .
    container_name: fastapi_app
    environment:
      - DB_URL=mysql+pymysql://root:1234@mysql:3306/expense_management_application_local
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app