version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: localhost
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: expense_management_application_local
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # Volumen para persistir los datos